name: Check Attributions

on:
  push:
    branches: Version-v*

jobs:
  check-attributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@4f594ca7d90378da66b7efce987eff379934524b

      - name: Check attributions changes
        run: yarn attributions:check
