name: Confirmations summary
on:
  push:
    paths:
      - ui/pages/confirmations/confirm/**
  pull_request:
    branches:
      - develop
    paths:
      - ui/pages/confirmations/confirm/**

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'You have made changes to `ui/pages/confirmations/confirm/` contact Confirmations UX to not break feature parity.!'
            })