name: Confirmations summary
on:
  push:
    paths:
      - ui/pages/confirmations/**
  pull_request:
    types: [ opened, reopened, edited ]
    branches:
      - develop
    paths:
      - ui/pages/confirmations/**

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: The confirmations are currently being redesigned. You have made changes to `ui/pages/confirmations/**`.  Ensure that your changes apply to both the old and redesigned screens. Contact the confirmations team before finalizing your changes. :warning:'
            })