name: Create Release Pull Request

on:
  workflow_dispatch:
    inputs:
      checkout-base-branch:
        description: 'The base branch, tag, or SHA for git operations. Usually `main`'
        required: true
      release-pr-base-branch:
        description: 'The base branch, tag, or SHA for the release pull request. Usually `master`'
        required: true
      semver-version:
        description: 'A semantic version, eg: x.x.x'
        required: true
      previous-version-ref:
        description: 'Previous release version branch name, tag or commit hash (e.g., Version-vx.y.z, v7.7.0, or 76fbc500034db9779e9ff7ce637ac5be1da0493d)'
        required: true

  workflow_call:
    inputs:
      checkout-base-branch:
        required: true
        type: string
      release-pr-base-branch:
        required: true
        type: string
      semver-version:
        required: true
        type: string
      previous-version-ref:
        required: true
        type: string
    secrets:
      github-token:
        required: false
      google-application-creds-base64:
        required: false

jobs:
  create-release-pr:
    name: Create Release Pull Request using Github Tools
    uses: MetaMask/github-tools/.github/workflows/create-release-pr.yml@914cbff8a8d58cfe0053e8690a3c0d4b281e27d6
    with:
      platform: extension
      checkout-base-branch: ${{ inputs.checkout-base-branch }}
      release-pr-base-branch: ${{ inputs.release-pr-base-branch }}
      semver-version: ${{ inputs.semver-version }}
      previous-version-ref: ${{ inputs.previous-version-ref }}
      github-tools-version: 914cbff8a8d58cfe0053e8690a3c0d4b281e27d6
    secrets:
      # This token needs write permissions to metamask-extension & read permissions to metamask-planning
      github-token: ${{ github.event_name == 'workflow_dispatch' && secrets.PR_TOKEN || secrets.github-token }}
      google-application-creds-base64: ${{ github.event_name == 'workflow_dispatch' && secrets.GCP_RLS_SHEET_ACCOUNT_BASE64 || secrets.google-application-creds-base64 }}
    permissions:
      contents: write
      pull-requests: write
