name: E2E Chrome

on:
  workflow_call:

jobs:
  get-changed-files-with-git-diff:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Get changed files with git diff
        run: yarn tsx .github/scripts/git-diff-default-branch.ts

      - name: Upload changed files artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

  prep-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - run: yarn build:test

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-e2e-tests
          path: ./dist/

  test-e2e-chrome:
    needs:
      - get-changed-files-with-git-diff
      - prep-build-test
    runs-on: ubuntu-22.04
    container:
      image: cimg/node:22.13-browsers
    strategy:
      fail-fast: false
      matrix:
        index:
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    env:
      MATRIX_INDEX: ${{ matrix.index }}
      MATRIX_TOTAL: ${{ strategy.job-total }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install zstd
          sudo corepack enable
        shell: bash

      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Install anvil (not installed by checkout-and-setup when cache is restored)
        run: yarn foundryup

      - name: Download prep-build-test artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-e2e-tests
          path: ./dist/

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Download changed-files artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

      - name: Run e2e tests
        timeout-minutes: 30
        run: yarn test:e2e:chrome

      - name: Upload test results and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-e2e-chrome-${{ matrix.index }}
          path: |
            ./test-artifacts
            ./test/test-results/e2e

  test-e2e-chrome-flask:
    needs:
      - get-changed-files-with-git-diff
    runs-on: ubuntu-22.04
    container:
      image: cimg/node:22.13-browsers
    strategy:
      fail-fast: false
      matrix:
        index: [0, 1, 2, 3, 4, 5, 6, 7]
    env:
      MATRIX_INDEX: ${{ matrix.index }}
      MATRIX_TOTAL: ${{ strategy.job-total }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install zstd
          sudo corepack enable
        shell: bash

      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Install anvil (not installed by checkout-and-setup when cache is restored)
        run: yarn foundryup

      - run: yarn build:test:flask

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Download changed-files artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

      - name: Run e2e tests
        timeout-minutes: 30
        run: yarn test:e2e:chrome:flask

      - name: Upload test results and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-e2e-chrome-flask-${{ matrix.index }}
          path: |
            ./test-artifacts
            ./test/test-results/e2e

  test-e2e-chrome-multiple-providers:
    uses: ./.github/workflows/run-e2e.yml
    with:
      test-suite-name: test-e2e-chrome-multiple-providers
      build-command: yarn build:test
      test-command: yarn test:e2e:chrome:multi-provider

  test-e2e-chrome-rpc:
    uses: ./.github/workflows/run-e2e.yml
    with:
      test-suite-name: test-e2e-chrome-rpc
      build-command: yarn build:test
      test-command: yarn test:e2e:chrome:rpc
