name: E2E Tests

on:
  workflow_call:

jobs:
  needs-e2e:
    name: Needs E2E
    runs-on: ubuntu-latest
    outputs:
      needs-e2e: ${{ steps.needs-e2e.outputs.NEEDS_E2E }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # By default, the checkout action checks out the last merge commit for pull requests.
          # Source: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
          # However, we need the head commit (the latest commit pushed to the source branch)
          # because in the workflow, we would like to parse the latest commit tag.
          # Specifying `ref` ensures that the head commit is checked out directly.
          # For a `pull_request` event, the head commit hash is `github.event.pull_request.head.sha`.
          # For a `push` event, the head commit hash is `github.sha`.
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Skip E2E
        id: needs-e2e
        env:
          HEAD_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          if git show --format='%B' --no-patch "${HEAD_COMMIT_HASH}" | grep --fixed-strings --quiet '[skip e2e]'; then
              printf '%s\n' "${HEAD_COMMIT_HASH} contains the tag '[skip e2e]' so e2e tests will not run"
              echo "NEEDS_E2E=false" >> "$GITHUB_OUTPUT"
          else
              printf '%s\n' "${HEAD_COMMIT_HASH} does not contain the tag '[skip e2e]' so e2e tests will run"
              echo "NEEDS_E2E=true" >> "$GITHUB_OUTPUT"
          fi

  get-changed-files-with-git-diff:
    needs:
      - needs-e2e
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' && needs.needs-e2e.outputs.needs-e2e == 'true' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Get changed files with git diff
        run: yarn tsx .github/scripts/git-diff-default-branch.ts

      - name: Upload changed files artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

  prep-build-test:
    needs:
      - needs-e2e
    if: ${{ needs.needs-e2e.outputs.needs-e2e == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - run: yarn build:test

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-e2e-tests
          path: ./dist/

  test-e2e-chrome:
    needs:
      - needs-e2e
      - get-changed-files-with-git-diff
      - prep-build-test
    if: ${{ needs.needs-e2e.outputs.needs-e2e == 'true' }}
    runs-on: ubuntu-22.04
    container:
      image: cimg/node:22.13-browsers
    strategy:
      fail-fast: false
      matrix:
        index:
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    env:
      MATRIX_INDEX: ${{ matrix.index }}
      MATRIX_TOTAL: ${{ strategy.job-total }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install zstd
          sudo corepack enable
        shell: bash

      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Install anvil (not installed by checkout-and-setup when cache is restored)
        run: yarn foundryup

      - name: Download prep-build-test artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-e2e-tests
          path: ./dist/

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Download changed-files artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

      - name: Run e2e tests
        timeout-minutes: 30
        run: yarn test:e2e:chrome

      - name: Upload test results and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-e2e-chrome-${{ matrix.index }}
          path: |
            ./test-artifacts
            ./test/test-results/e2e

  test-e2e-chrome-flask:
    needs:
      - needs-e2e
      - get-changed-files-with-git-diff
    if: ${{ needs.needs-e2e.outputs.needs-e2e == 'true' }}
    runs-on: ubuntu-22.04
    container:
      image: cimg/node:22.13-browsers
    strategy:
      fail-fast: false
      matrix:
        index: [0, 1, 2, 3, 4, 5, 6, 7]
    env:
      MATRIX_INDEX: ${{ matrix.index }}
      MATRIX_TOTAL: ${{ strategy.job-total }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install zstd
          sudo corepack enable
        shell: bash

      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Install anvil (not installed by checkout-and-setup when cache is restored)
        run: yarn foundryup

      - run: yarn build:test:flask

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Download changed-files artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

      - name: Run e2e tests
        timeout-minutes: 30
        run: yarn test:e2e:chrome:flask

      - name: Upload test results and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-e2e-chrome-flask-${{ matrix.index }}
          path: |
            ./test-artifacts
            ./test/test-results/e2e

  test-e2e-chrome-multiple-providers:
    needs:
      - needs-e2e
      - prep-build-test
      - get-changed-files-with-git-diff
    if: ${{ needs.needs-e2e.outputs.needs-e2e == 'true' }}
    runs-on: ubuntu-22.04
    container:
      image: cimg/node:22.13-browsers
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install zstd
          sudo corepack enable
        shell: bash

      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Install anvil (not installed by checkout-and-setup when cache is restored)
        run: yarn foundryup

      - name: Download prep-build-test artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-e2e-tests
          path: ./dist/

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Download changed-files artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

      - name: Run e2e tests
        timeout-minutes: 30
        run: yarn test:e2e:chrome:multi-provider

      - name: Upload test results and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-e2e-chrome-multiple-providers
          path: |
            ./test-artifacts
            ./test/test-results/e2e

  test-e2e-chrome-rpc:
    needs:
      - needs-e2e
      - prep-build-test
      - get-changed-files-with-git-diff
    if: ${{ needs.needs-e2e.outputs.needs-e2e == 'true' }}
    runs-on: ubuntu-22.04
    container:
      image: cimg/node:22.13-browsers
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install zstd
          sudo corepack enable
        shell: bash

      - name: Checkout and setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@1299bb1de0c6974ae6d0a32c7e8897fe168239ac
        with:
          is-high-risk-environment: false

      - name: Install anvil (not installed by checkout-and-setup when cache is restored)
        run: yarn foundryup

      - name: Download prep-build-test artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-e2e-tests
          path: ./dist/

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Download changed-files artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: changed-files
          path: ./changed-files/

      - name: Run e2e tests
        timeout-minutes: 30
        run: yarn test:e2e:chrome:rpc

      - name: Upload test results and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-e2e-chrome-rpc
          path: |
            ./test-artifacts
            ./test/test-results/e2e
