name: Test lint changelog

on:
  workflow_call:

jobs:
  test-lint-changelog:
    name: Test lint changelog
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@main

      - name: Validate changelog
        id: validate-changelog
        # For a `pull_request` event, the branch is `github.head_ref`.
        # For a `push` event, the branch is `github.ref_name`.
        if: ${{ !startsWith(github.head_ref || github.ref_name, 'Version-v') }}
        run: |
          if yarn lint:changelog; then
            echo "result=success" >> $GITHUB_ENV
          else
            echo "result=failure" >> $GITHUB_ENV
          fi

      - name: Validate release candidate changelog
        id: validate-rc-changelog
        # For a `pull_request` event, the branch is `github.head_ref`.
        # For a `push` event, the branch is `github.ref_name`.
        if: ${{ startsWith(github.head_ref || github.ref_name, 'Version-v') }}
        run: |
          if .circleci/scripts/validate-changelog-in-rc.sh; then
            echo "result=success" >> $GITHUB_ENV
          else
            echo "result=failure" >> $GITHUB_ENV
          fi

      - name: Set result
        id: set-result
        run: echo "result=${{ env.result }}" >> $GITHUB_OUTPUT
