name: Test lint changelog

on:
  workflow_call:

jobs:
  test-lint-changelog:
    name: Test lint changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@main

      - name: Validate changelog
        id: validate-changelog
        # For a `pull_request` event, the branch is `github.head_ref`.
        # For a `push` event, the branch is `github.ref_name`.
        if: ${{ !startsWith(github.head_ref || github.ref_name, 'Version-v') }}
        run: |
          if yarn lint:changelog; then
            echo "CHANGELOG_LINT_RESULT=success" >> $GITHUB_ENV
          else
            echo "CHANGELOG_LINT_RESULT=failure" >> $GITHUB_ENV
          fi
          echo "Changelog Lint Result: $CHANGELOG_LINT_RESULT"

      - name: Validate release candidate changelog
        id: validate-rc-changelog
        # For a `pull_request` event, the branch is `github.head_ref`.
        # For a `push` event, the branch is `github.ref_name`.
        if: ${{ startsWith(github.head_ref || github.ref_name, 'Version-v') }}
        run: |
          if .circleci/scripts/validate-changelog-in-rc.sh; then
            echo "CHANGELOG_LINT_RESULT=success" >> $GITHUB_ENV
          else
            echo "CHANGELOG_LINT_RESULT=failure" >> $GITHUB_ENV
          fi
          echo "Changelog Lint Result: ${{ env.CHANGELOG_LINT_RESULT }}"

      - name: Fail job if result is failure
        if: ${{ env.CHANGELOG_LINT_RESULT == 'failure' }}
        run: exit 1
