name: Test Optimize Images

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-optimize-images:
    name: Test image optimization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true
          yarn-custom-url: ${{ vars.YARN_URL }}
      - name: Test optimize images
        run: |
          echo "Testing image optimization..."
          yarn lint:images:fix
          echo "Image optimization test completed"
      - name: Check for changes
        run: |
          if git diff --exit-code
          then
            echo "No changes detected"
          else
            echo "Changes detected:"
            git diff --name-only
          fi
